# Generated by Django 4.0.5 on 2022-10-10 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('department', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('initial', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
            ],
            options={
                'db_table': 'master',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('salary', models.FloatField()),
                ('address', models.TextField(max_length=20)),
                ('DOJ', models.DateField(auto_now_add=True, verbose_name='doj')),
                ('emp_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_name', to='account.department')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
